spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: file:${JWT_PUBLIC_KEY_PATH}

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-refresh
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/refresh
                - Method=POST
              filters:
                - RewritePath=/api/refresh, /api/auth/refresh

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URL}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG