services:

  api-gateway:
    image: pixelchiss-gateway:latest
    container_name: pixelchiss-gateway
    restart: unless-stopped

    environment:
      EUREKA_URL: ${EUREKA_URL}
      JWT_PUBLIC_KEY_PATH: ${JWT_PUBLIC_KEY_PATH}

    ports:
      - "8080:8080"

    volumes:
      - ../../api-gateway/keys:/app/keys:ro

    depends_on:
      - eureka-server

    networks:
      - pixelchiss-network

  eureka-server:
    image: pixelchiss-eureka:latest
    container_name: pixelchiss-eureka
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - pixelchiss-network

  auth-service:
    image: pixelchiss-auth:latest
    container_name: pixelchiss-auth
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      EUREKA_URL: ${EUREKA_URL}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      JWT_PRIVATE_KEY_PATH: ${JWT_PRIVATE_KEY_PATH}
      JWT_PUBLIC_KEY_PATH: ${JWT_PUBLIC_KEY_PATH}

    ports:
      - "8081:8081"

    volumes:
      - ../../auth-service/keys:/app/keys:ro

    depends_on:
      - eureka-server
      - postgres

    networks:
      - pixelchiss-network

  postgres:
    image: postgres:17
    container_name: pixelchiss-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pixelchiss-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: pixelchiss-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: pixelchiss
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pixelchiss-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: pixelchiss-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pixelchiss-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  pixelchiss-network:
    driver: bridge